### ISSUE TITLE
Need help understanding this error

### ISSUE THREAD

**Issue by wicadmin** [kk7ds/pynx584#16]
Does this mean it is sending binary data?
```
bash-4.4# nx584_server --serial /dev/ttyS0 --baud 38400
2018-03-14 20:27:09,018 main INFO Ready
2018-03-14 20:27:09,030 controller INFO Loaded extensions []
2018-03-14 20:27:09,036 _internal INFO  * Running on http://127.0.0.1:5007/ (Press CTRL+C to quit)
2018-03-14 20:27:09,283 controller ERROR Failed to parse raw ASCII line '\x00'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nx584/controller.py", line 229, in process_next
    line = parse_ascii(data)
  File "/usr/lib/python2.7/site-packages/nx584/controller.py", line 24, in parse_ascii
    data_bytes.append(int(data[i:i + 2], 16))
ValueError: invalid literal for int() with base 16: '\x00'
```

**Comment by kk7ds** [comment]
Yep, likely that's what it means.

**Comment by kk7ds** [comment]
Meaning, there are other things that could cause that, like reading a stream from the wrong serial device, or some driver/hardware failure. But if things are working, and you get that from the nx584, then it's in binary mode.

**Comment by wicadmin** [comment]
Thanks....I'm using a NX-8E plugged into a mITX board that has a single serial port. I am using the P-0003 cable connected to a rs-232 null modem adapter then to the mITX board. 

Are there some other things I can try to debug what is going on? Not sure why binary is being sent if it is set to ascii. Is there a raw dump of what is coming out the port that can be printed out?

**Comment by kk7ds** [comment]
you can use something like minicom to open the serial port at the right baud rate and you should see stuff streaming in from the panel. If it's ascii, they'll be short neat lines of all readable characters. If binary, it will be garbage.

Another thing that could do this I guess is an invalid baud rate.

**Comment by wicadmin** [comment]
k..will try that. I tried changing to 115200, and no errors, but also nothing on summary:

```
bash-4.4# nx584_server --serial /dev/ttyS0 --baud 115200
2018-03-14 21:13:55,513 main INFO Ready
2018-03-14 21:13:55,526 controller INFO Loaded extensions []
2018-03-14 21:13:55,531 _internal INFO  * Running on http://127.0.0.1:5007/ (Press CTRL+C to quit)
2018-03-14 21:13:59,039 _internal INFO 127.0.0.1 - - [14/Mar/2018 21:13:59] "GET /zones HTTP/1.1" 200 -
2018-03-14 21:13:59,052 _internal INFO 127.0.0.1 - - [14/Mar/2018 21:13:59] "GET /partitions HTTP/1.1" 200 -
```

**Comment by wicadmin** [comment]
I use minicom, but I am seeing absolutely nothing coming out. I wonder if there is anything else that could be disabling the serial port other that location 207 (which is set to 1)

**Comment by zipperten** [comment]
Hi i love this program! 

Thanks for the great panel configuration guide, i have connected it and get status from my alarm i would gladly contribute with some pin connection info and stuff later.  I get reports from my 27 zones, i have some on 44 but that are wireless smoke sensors, the do not constantly report to the panel so they maybe show up later.

I got some error messages when i start, and it did not create the config.ini file so it starts from the beginning with 0 unnamed zones every time.  i paste the log down here 

https://paste.ubuntu.com/p/gnQctBpDpK/
Thanks Daniel
