### ISSUE TITLE
Getting this error - TypeError: getboolean() got an unexpected keyword argument 'fallback'

### ISSUE THREAD

**Issue by wicadmin** [kk7ds/pynx584#17]
```
TypeError: getboolean() got an unexpected keyword argument 'fallback'
2018-03-24 18:09:42,833 controller ERROR Failed to process message type 10
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nx584/controller.py", line 610, in controller_loop
    getattr(self, name)(frame)
  File "/usr/lib/python2.7/site-packages/nx584/controller.py", line 509, in process_msg_10
    fallback=False)
TypeError: getboolean() got an unexpected keyword argument 'fallback'
2018-03-24 18:09:43,183 controller ERROR Failed to process message type 10
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nx584/controller.py", line 610, in controller_loop
    getattr(self, name)(frame)
  File "/usr/lib/python2.7/site-packages/nx584/controller.py", line 509, in process_msg_10
    fallback=False)
TypeError: getboolean() got an unexpected keyword argument 'fallback'
2018-03-24 18:09:43,532 controller ERROR Failed to process message type 10
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nx584/controller.py", line 610, in controller_loop
    getattr(self, name)(frame)
  File "/usr/lib/python2.7/site-packages/nx584/controller.py", line 509, in process_msg_10
    fallback=False)
TypeError: getboolean() got an unexpected keyword argument 'fallback'
```

**Comment by wicadmin** [comment]
Closing...looks to be an issue only with python 2. Using Python 3 now.
