### ISSUE TITLE
Have to restart home assistant every day because no response from the server

### ISSUE THREAD

**Issue by Ziepoeskenetnie** [kk7ds/pynx584#83]
Doors are not showing open every day now and then after restart it's all okay again. Happens few times a day.

**Comment by Ziepoeskenetnie** [comment]
Logger: homeassistant.helpers.entity
Source: components/nx584/alarm_control_panel.py:135
First occurred: 23:04:20 (72 occurrences)
Last logged: 23:16:11

Update for alarm_control_panel.nx584 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 940, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/nx584/alarm_control_panel.py", line 135, in update
    if not part["armed"]:
           ^^^^
UnboundLocalError: cannot access local variable 'part' where it is not associated with a value

**Comment by kk7ds** [comment]
That's a bug in the homeassistant module, not pynx584.
